"""Notification texts in the panel's 17 languages (#68).

Keys of NOTIFY_TEXT are the panel's language codes (scheduler.panel_lang maps the HA language).
"valve_done" is the panel's "home.act_watered" in every language (tests/test_i18n.py keeps them equal).
"""
from __future__ import annotations

from typing import Any

APP_TITLE = "Schedule Wizard"

NOTIFY_TEXT: dict[str, dict[str, str]] = {
    "en": {
        "valve_start": "{zone} started, {n} min",
        "valve_done": "{zone} watered {n} min",
        "valve_stopped": "{zone} stopped",
        "valve_failed": "{zone} did not open",
        "cycle_start": "{plan} started, {n} min",
        "cycle_done": "{plan} finished",
        "cycle_stopped": "{plan} stopped",
        "skip_rain": "{name} skipped: it is raining",
        "skip_forecast": "{name} skipped: rain is forecast",
        "skip_rain_delay": "{name} skipped: paused for rain",
        "skip_moisture": "{name} skipped: the soil is moist enough",
        "skip_condition": "{name} skipped: a condition was not met",
        "rain_pause_all": "Watering paused for {hours} h (rain)",
        "rain_pause_zones": "{zones}: watering paused for {hours} h (rain)",
        "rain_pause_end_all": "Rain pause ended for all zones",
        "rain_pause_end_zones": "Rain pause ended: {zones}",
        "leak": "Possible leak: water is flowing ({value}) while no zone is running",
        "high_flow": "High flow ({value}) while watering {zones}",
        "stopped_all": "All watering stopped.",
        "low_flow": "Low flow on {zone}: {lpm} L/min, usually {avg}. Check the filter, valve or pipe.",
        "reminder_title": "Watering soon",
        "reminder_body": "{name} starts at {time} ({n} min).",
        "reminder_skip": "Skip today",
        "reminder_run": "Water now",
    },
    "de": {
        "valve_start": "{zone} gestartet, {n} Min.",
        "valve_done": "{zone}: {n} Min. bewässert",
        "valve_stopped": "{zone} gestoppt",
        "valve_failed": "{zone} hat nicht geöffnet",
        "cycle_start": "{plan} gestartet, {n} Min.",
        "cycle_done": "{plan} beendet",
        "cycle_stopped": "{plan} gestoppt",
        "skip_rain": "{name} übersprungen: es regnet",
        "skip_forecast": "{name} übersprungen: Regen vorhergesagt",
        "skip_rain_delay": "{name} übersprungen: Regenpause",
        "skip_moisture": "{name} übersprungen: der Boden ist feucht genug",
        "skip_condition": "{name} übersprungen: eine Bedingung war nicht erfüllt",
        "rain_pause_all": "Bewässerung für {hours} Std. pausiert (Regen)",
        "rain_pause_zones": "{zones}: Bewässerung für {hours} Std. pausiert (Regen)",
        "rain_pause_end_all": "Regenpause für alle Zonen beendet",
        "rain_pause_end_zones": "Regenpause beendet: {zones}",
        "leak": "Mögliches Leck: Wasser fließt ({value}), obwohl keine Zone läuft",
        "high_flow": "Hoher Durchfluss ({value}) beim Bewässern von {zones}",
        "stopped_all": "Alle Bewässerungen gestoppt.",
        "low_flow": "Geringer Durchfluss bei {zone}: {lpm} L/min, sonst {avg}. Filter, Ventil oder Leitung prüfen.",
        "reminder_title": "Bewässerung gleich",
        "reminder_body": "{name} startet um {time} ({n} Min.).",
        "reminder_skip": "Heute überspringen",
        "reminder_run": "Jetzt bewässern",
    },
    "he": {
        "valve_start": "{zone}: ההשקיה התחילה, {n} דק׳",
        "valve_done": "{zone}: השקיה של {n} דק׳",
        "valve_stopped": "{zone}: ההשקיה הופסקה",
        "valve_failed": "{zone}: הברז לא נפתח",
        "cycle_start": "{plan}: התוכנית התחילה, {n} דק׳",
        "cycle_done": "{plan}: התוכנית הסתיימה",
        "cycle_stopped": "{plan}: התוכנית הופסקה",
        "skip_rain": "{name}: דולג, יורד גשם",
        "skip_forecast": "{name}: דולג, צפוי גשם",
        "skip_rain_delay": "{name}: דולג, השהיית גשם",
        "skip_moisture": "{name}: דולג, האדמה לחה מספיק",
        "skip_condition": "{name}: דולג, תנאי לא התקיים",
        "rain_pause_all": "ההשקיה מושהית ל־{hours} שע׳ (גשם)",
        "rain_pause_zones": "{zones}: ההשקיה מושהית ל־{hours} שע׳ (גשם)",
        "rain_pause_end_all": "השהיית הגשם הסתיימה בכל האזורים",
        "rain_pause_end_zones": "השהיית הגשם הסתיימה: {zones}",
        "leak": "חשד לדליפה: יש זרימת מים ({value}) כשאף אזור לא פועל",
        "high_flow": "זרימה גבוהה ({value}) בזמן השקיית {zones}",
        "stopped_all": "כל ההשקיות הופסקו.",
        "low_flow": "זרימה נמוכה ב־{zone}: {lpm} ל׳/דק׳, בדרך כלל {avg}. כדאי לבדוק את המסנן, הברז או הצינור.",
        "reminder_title": "השקיה בקרוב",
        "reminder_body": "{name} מתחיל ב־{time} ({n} דק׳).",
        "reminder_skip": "דילוג היום",
        "reminder_run": "השקיה עכשיו",
    },
    "es": {
        "valve_start": "{zone}: riego iniciado, {n} min",
        "valve_done": "{zone} regó {n} min",
        "valve_stopped": "{zone}: riego detenido",
        "valve_failed": "{zone}: la válvula no se abrió",
        "cycle_start": "{plan}: plan iniciado, {n} min",
        "cycle_done": "{plan}: plan terminado",
        "cycle_stopped": "{plan}: plan detenido",
        "skip_rain": "{name}: riego omitido, está lloviendo",
        "skip_forecast": "{name}: riego omitido, se prevé lluvia",
        "skip_rain_delay": "{name}: riego omitido, pausa por lluvia",
        "skip_moisture": "{name}: riego omitido, el suelo está bastante húmedo",
        "skip_condition": "{name}: riego omitido, no se cumplió una condición",
        "rain_pause_all": "Riego en pausa durante {hours} h (lluvia)",
        "rain_pause_zones": "{zones}: riego en pausa durante {hours} h (lluvia)",
        "rain_pause_end_all": "Fin de la pausa por lluvia en todas las zonas",
        "rain_pause_end_zones": "Fin de la pausa por lluvia: {zones}",
        "leak": "Posible fuga: hay caudal ({value}) sin ninguna zona en marcha",
        "high_flow": "Caudal alto ({value}) mientras riega {zones}",
        "stopped_all": "Se detuvo todo el riego.",
        "low_flow": "Caudal bajo en {zone}: {lpm} L/min, normalmente {avg}. Revisa el filtro, la válvula o la tubería.",
        "reminder_title": "Riego en breve",
        "reminder_body": "{name} empieza a las {time} ({n} min).",
        "reminder_skip": "Omitir hoy",
        "reminder_run": "Regar ahora",
    },
    "fr": {
        "valve_start": "{zone} : arrosage démarré, {n} min",
        "valve_done": "{zone} arrosée {n} min",
        "valve_stopped": "{zone} : arrosage arrêté",
        "valve_failed": "{zone} : la vanne ne s'est pas ouverte",
        "cycle_start": "{plan} : programme démarré, {n} min",
        "cycle_done": "{plan} : programme terminé",
        "cycle_stopped": "{plan} : programme arrêté",
        "skip_rain": "{name} : arrosage ignoré, il pleut",
        "skip_forecast": "{name} : arrosage ignoré, pluie prévue",
        "skip_rain_delay": "{name} : arrosage ignoré, pause pluie",
        "skip_moisture": "{name} : arrosage ignoré, le sol est assez humide",
        "skip_condition": "{name} : arrosage ignoré, une condition n'était pas remplie",
        "rain_pause_all": "Arrosage en pause pendant {hours} h (pluie)",
        "rain_pause_zones": "{zones} : arrosage en pause pendant {hours} h (pluie)",
        "rain_pause_end_all": "Fin de la pause pluie pour toutes les zones",
        "rain_pause_end_zones": "Fin de la pause pluie : {zones}",
        "leak": "Fuite possible : l'eau coule ({value}) alors qu'aucune zone n'est active",
        "high_flow": "Débit élevé ({value}) pendant l'arrosage de {zones}",
        "stopped_all": "Tout l'arrosage est arrêté.",
        "low_flow": "Débit faible sur {zone} : {lpm} L/min, d'habitude {avg}. Vérifiez le filtre, la vanne ou le tuyau.",
        "reminder_title": "Arrosage bientôt",
        "reminder_body": "{name} démarre à {time} ({n} min).",
        "reminder_skip": "Ignorer aujourd'hui",
        "reminder_run": "Arroser maintenant",
    },
    "it": {
        "valve_start": "{zone}: irrigazione avviata, {n} min",
        "valve_done": "{zone} irrigata {n} min",
        "valve_stopped": "{zone}: irrigazione fermata",
        "valve_failed": "{zone}: la valvola non si è aperta",
        "cycle_start": "{plan}: piano avviato, {n} min",
        "cycle_done": "{plan}: piano completato",
        "cycle_stopped": "{plan}: piano fermato",
        "skip_rain": "{name}: irrigazione saltata, sta piovendo",
        "skip_forecast": "{name}: irrigazione saltata, prevista pioggia",
        "skip_rain_delay": "{name}: irrigazione saltata, pausa pioggia",
        "skip_moisture": "{name}: irrigazione saltata, il terreno è abbastanza umido",
        "skip_condition": "{name}: irrigazione saltata, una condizione non era soddisfatta",
        "rain_pause_all": "Irrigazione in pausa per {hours} h (pioggia)",
        "rain_pause_zones": "{zones}: irrigazione in pausa per {hours} h (pioggia)",
        "rain_pause_end_all": "Pausa pioggia terminata per tutte le zone",
        "rain_pause_end_zones": "Pausa pioggia terminata: {zones}",
        "leak": "Possibile perdita: l'acqua scorre ({value}) ma nessuna zona è attiva",
        "high_flow": "Flusso elevato ({value}) durante l'irrigazione di {zones}",
        "stopped_all": "Tutta l'irrigazione è stata fermata.",
        "low_flow": "Flusso basso su {zone}: {lpm} L/min, di solito {avg}. Controlla filtro, valvola o tubo.",
        "reminder_title": "Irrigazione a breve",
        "reminder_body": "{name} inizia alle {time} ({n} min).",
        "reminder_skip": "Salta oggi",
        "reminder_run": "Irriga ora",
    },
    "nl": {
        "valve_start": "{zone}: sproeien gestart, {n} min",
        "valve_done": "{zone} {n} min gesproeid",
        "valve_stopped": "{zone}: sproeien gestopt",
        "valve_failed": "{zone}: de klep ging niet open",
        "cycle_start": "{plan}: plan gestart, {n} min",
        "cycle_done": "{plan}: plan klaar",
        "cycle_stopped": "{plan}: plan gestopt",
        "skip_rain": "{name} overgeslagen: het regent",
        "skip_forecast": "{name} overgeslagen: regen verwacht",
        "skip_rain_delay": "{name} overgeslagen: regenpauze",
        "skip_moisture": "{name} overgeslagen: de grond is vochtig genoeg",
        "skip_condition": "{name} overgeslagen: een voorwaarde was niet vervuld",
        "rain_pause_all": "Sproeien {hours} u gepauzeerd (regen)",
        "rain_pause_zones": "{zones}: sproeien {hours} u gepauzeerd (regen)",
        "rain_pause_end_all": "Regenpauze beëindigd voor alle zones",
        "rain_pause_end_zones": "Regenpauze beëindigd: {zones}",
        "leak": "Mogelijk lek: er stroomt water ({value}) terwijl geen zone actief is",
        "high_flow": "Hoge doorstroming ({value}) tijdens sproeien van {zones}",
        "stopped_all": "Alle sproeibeurten gestopt.",
        "low_flow": "Lage doorstroming bij {zone}: {lpm} L/min, meestal {avg}. Controleer filter, klep of leiding.",
        "reminder_title": "Zo meteen sproeien",
        "reminder_body": "{name} start om {time} ({n} min).",
        "reminder_skip": "Vandaag overslaan",
        "reminder_run": "Nu sproeien",
    },
    "pt": {
        "valve_start": "{zone}: rega iniciada, {n} min",
        "valve_done": "{zone} regou {n} min",
        "valve_stopped": "{zone}: rega parada",
        "valve_failed": "{zone}: a válvula não abriu",
        "cycle_start": "{plan}: plano iniciado, {n} min",
        "cycle_done": "{plan}: plano concluído",
        "cycle_stopped": "{plan}: plano parado",
        "skip_rain": "{name}: rega ignorada, está a chover",
        "skip_forecast": "{name}: rega ignorada, prevê-se chuva",
        "skip_rain_delay": "{name}: rega ignorada, pausa por chuva",
        "skip_moisture": "{name}: rega ignorada, o solo está húmido o suficiente",
        "skip_condition": "{name}: rega ignorada, uma condição não se cumpriu",
        "rain_pause_all": "Rega em pausa durante {hours} h (chuva)",
        "rain_pause_zones": "{zones}: rega em pausa durante {hours} h (chuva)",
        "rain_pause_end_all": "Pausa por chuva terminada em todas as zonas",
        "rain_pause_end_zones": "Pausa por chuva terminada: {zones}",
        "leak": "Possível fuga: há caudal ({value}) sem nenhuma zona ativa",
        "high_flow": "Caudal alto ({value}) durante a rega de {zones}",
        "stopped_all": "Toda a rega foi parada.",
        "low_flow": "Caudal baixo em {zone}: {lpm} L/min, normalmente {avg}. Verifique o filtro, a válvula ou o tubo.",
        "reminder_title": "Rega em breve",
        "reminder_body": "{name} começa às {time} ({n} min).",
        "reminder_skip": "Ignorar hoje",
        "reminder_run": "Regar agora",
    },
    "ru": {
        "valve_start": "{zone}: полив начат, {n} мин.",
        "valve_done": "{zone}: полив {n} мин.",
        "valve_stopped": "{zone}: полив остановлен",
        "valve_failed": "{zone}: клапан не открылся",
        "cycle_start": "{plan}: программа запущена, {n} мин.",
        "cycle_done": "{plan}: программа завершена",
        "cycle_stopped": "{plan}: программа остановлена",
        "skip_rain": "{name}: полив пропущен, идёт дождь",
        "skip_forecast": "{name}: полив пропущен, ожидается дождь",
        "skip_rain_delay": "{name}: полив пропущен, пауза из-за дождя",
        "skip_moisture": "{name}: полив пропущен, почва достаточно влажная",
        "skip_condition": "{name}: полив пропущен, условие не выполнено",
        "rain_pause_all": "Полив приостановлен на {hours} ч (дождь)",
        "rain_pause_zones": "{zones}: полив приостановлен на {hours} ч (дождь)",
        "rain_pause_end_all": "Пауза из-за дождя снята для всех зон",
        "rain_pause_end_zones": "Пауза из-за дождя снята: {zones}",
        "leak": "Возможна утечка: вода течёт ({value}), хотя ни одна зона не работает",
        "high_flow": "Высокий расход ({value}) во время полива: {zones}",
        "stopped_all": "Весь полив остановлен.",
        "low_flow": "Низкий расход в зоне {zone}: {lpm} л/мин, обычно {avg}. Проверьте фильтр, клапан или трубу.",
        "reminder_title": "Скоро полив",
        "reminder_body": "{name} начнётся в {time} ({n} мин.).",
        "reminder_skip": "Пропустить сегодня",
        "reminder_run": "Полить сейчас",
    },
    "uk": {
        "valve_start": "{zone}: полив розпочато, {n} хв",
        "valve_done": "{zone}: полив {n} хв",
        "valve_stopped": "{zone}: полив зупинено",
        "valve_failed": "{zone}: клапан не відкрився",
        "cycle_start": "{plan}: програму запущено, {n} хв",
        "cycle_done": "{plan}: програму завершено",
        "cycle_stopped": "{plan}: програму зупинено",
        "skip_rain": "{name}: полив пропущено, йде дощ",
        "skip_forecast": "{name}: полив пропущено, очікується дощ",
        "skip_rain_delay": "{name}: полив пропущено, пауза через дощ",
        "skip_moisture": "{name}: полив пропущено, ґрунт достатньо вологий",
        "skip_condition": "{name}: полив пропущено, умову не виконано",
        "rain_pause_all": "Полив призупинено на {hours} год (дощ)",
        "rain_pause_zones": "{zones}: полив призупинено на {hours} год (дощ)",
        "rain_pause_end_all": "Паузу через дощ знято для всіх зон",
        "rain_pause_end_zones": "Паузу через дощ знято: {zones}",
        "leak": "Можливий витік: вода тече ({value}), хоча жодна зона не працює",
        "high_flow": "Високий потік ({value}) під час поливу: {zones}",
        "stopped_all": "Увесь полив зупинено.",
        "low_flow": "Низький потік у зоні {zone}: {lpm} л/хв, зазвичай {avg}. Перевірте фільтр, клапан або трубу.",
        "reminder_title": "Незабаром полив",
        "reminder_body": "{name} почнеться о {time} ({n} хв).",
        "reminder_skip": "Пропустити сьогодні",
        "reminder_run": "Полити зараз",
    },
    "pl": {
        "valve_start": "{zone}: podlewanie rozpoczęte, {n} min",
        "valve_done": "{zone}: podlewanie {n} min",
        "valve_stopped": "{zone}: podlewanie zatrzymane",
        "valve_failed": "{zone}: zawór się nie otworzył",
        "cycle_start": "{plan}: plan uruchomiony, {n} min",
        "cycle_done": "{plan}: plan zakończony",
        "cycle_stopped": "{plan}: plan zatrzymany",
        "skip_rain": "{name}: pominięto podlewanie, pada deszcz",
        "skip_forecast": "{name}: pominięto podlewanie, prognozowany deszcz",
        "skip_rain_delay": "{name}: pominięto podlewanie, przerwa na deszcz",
        "skip_moisture": "{name}: pominięto podlewanie, gleba jest wystarczająco wilgotna",
        "skip_condition": "{name}: pominięto podlewanie, warunek nie został spełniony",
        "rain_pause_all": "Podlewanie wstrzymane na {hours} h (deszcz)",
        "rain_pause_zones": "{zones}: podlewanie wstrzymane na {hours} h (deszcz)",
        "rain_pause_end_all": "Koniec przerwy na deszcz we wszystkich strefach",
        "rain_pause_end_zones": "Koniec przerwy na deszcz: {zones}",
        "leak": "Możliwy wyciek: woda płynie ({value}), choć żadna strefa nie działa",
        "high_flow": "Wysoki przepływ ({value}) podczas podlewania: {zones}",
        "stopped_all": "Całe podlewanie zatrzymane.",
        "low_flow": "Niski przepływ w strefie {zone}: {lpm} l/min, zwykle {avg}. Sprawdź filtr, zawór lub rurę.",
        "reminder_title": "Wkrótce podlewanie",
        "reminder_body": "{name} zaczyna o {time} ({n} min).",
        "reminder_skip": "Pomiń dzisiaj",
        "reminder_run": "Podlej teraz",
    },
    "ar": {
        "valve_start": "{zone}: بدأ الري، {n} دقيقة",
        "valve_done": "{zone} رُويت {n} دقيقة",
        "valve_stopped": "{zone}: توقف الري",
        "valve_failed": "{zone}: لم يُفتح الصمام",
        "cycle_start": "{plan}: بدأت الخطة، {n} دقيقة",
        "cycle_done": "{plan}: انتهت الخطة",
        "cycle_stopped": "{plan}: توقفت الخطة",
        "skip_rain": "{name}: تم تخطي الري، إنها تمطر",
        "skip_forecast": "{name}: تم تخطي الري، يُتوقع هطول مطر",
        "skip_rain_delay": "{name}: تم تخطي الري، إيقاف بسبب المطر",
        "skip_moisture": "{name}: تم تخطي الري، التربة رطبة بما يكفي",
        "skip_condition": "{name}: تم تخطي الري، لم يتحقق أحد الشروط",
        "rain_pause_all": "الري متوقف مؤقتًا لمدة {hours} ساعة (مطر)",
        "rain_pause_zones": "{zones}: الري متوقف مؤقتًا لمدة {hours} ساعة (مطر)",
        "rain_pause_end_all": "انتهى الإيقاف بسبب المطر لكل المناطق",
        "rain_pause_end_zones": "انتهى الإيقاف بسبب المطر: {zones}",
        "leak": "تسرب محتمل: المياه تتدفق ({value}) ولا توجد منطقة تعمل",
        "high_flow": "تدفق مرتفع ({value}) أثناء ري {zones}",
        "stopped_all": "تم إيقاف كل الري.",
        "low_flow": "تدفق منخفض في {zone}: {lpm} لتر/دقيقة، عادةً {avg}. افحص المرشح أو الصمام أو الأنبوب.",
        "reminder_title": "الري قريبًا",
        "reminder_body": "{name} يبدأ الساعة {time} ({n} دقيقة).",
        "reminder_skip": "تخطي اليوم",
        "reminder_run": "اسقِ الآن",
    },
    "zh-hans": {
        "valve_start": "{zone} 已开始浇水，{n} 分钟",
        "valve_done": "{zone} 已浇水 {n} 分钟",
        "valve_stopped": "{zone} 已停止浇水",
        "valve_failed": "{zone} 阀门未打开",
        "cycle_start": "{plan} 已开始，{n} 分钟",
        "cycle_done": "{plan} 已完成",
        "cycle_stopped": "{plan} 已停止",
        "skip_rain": "{name} 已跳过：正在下雨",
        "skip_forecast": "{name} 已跳过：预报有雨",
        "skip_rain_delay": "{name} 已跳过：雨天暂停",
        "skip_moisture": "{name} 已跳过：土壤足够湿润",
        "skip_condition": "{name} 已跳过：条件未满足",
        "rain_pause_all": "浇水已暂停 {hours} 小时（下雨）",
        "rain_pause_zones": "{zones}：浇水已暂停 {hours} 小时（下雨）",
        "rain_pause_end_all": "所有区域的雨天暂停已结束",
        "rain_pause_end_zones": "雨天暂停已结束：{zones}",
        "leak": "可能漏水：没有区域运行时仍有水流（{value}）",
        "high_flow": "浇灌 {zones} 时水流过大（{value}）",
        "stopped_all": "已停止所有浇水。",
        "low_flow": "{zone} 水流过小：{lpm} 升/分钟，通常为 {avg}。请检查过滤器、阀门或管道。",
        "reminder_title": "即将浇水",
        "reminder_body": "{name} 将于 {time} 开始（{n} 分钟）。",
        "reminder_skip": "今天跳过",
        "reminder_run": "立即浇水",
    },
    "sv": {
        "valve_start": "{zone}: bevattning startad, {n} min",
        "valve_done": "{zone} vattnades {n} min",
        "valve_stopped": "{zone}: bevattning stoppad",
        "valve_failed": "{zone}: ventilen öppnades inte",
        "cycle_start": "{plan}: plan startad, {n} min",
        "cycle_done": "{plan}: plan klar",
        "cycle_stopped": "{plan}: plan stoppad",
        "skip_rain": "{name} överhoppad: det regnar",
        "skip_forecast": "{name} överhoppad: regn väntas",
        "skip_rain_delay": "{name} överhoppad: regnpaus",
        "skip_moisture": "{name} överhoppad: jorden är tillräckligt fuktig",
        "skip_condition": "{name} överhoppad: ett villkor uppfylldes inte",
        "rain_pause_all": "Bevattning pausad i {hours} h (regn)",
        "rain_pause_zones": "{zones}: bevattning pausad i {hours} h (regn)",
        "rain_pause_end_all": "Regnpausen är slut för alla zoner",
        "rain_pause_end_zones": "Regnpausen är slut: {zones}",
        "leak": "Möjligt läckage: vatten flödar ({value}) fast ingen zon körs",
        "high_flow": "Högt flöde ({value}) under bevattning av {zones}",
        "stopped_all": "All bevattning stoppad.",
        "low_flow": "Lågt flöde på {zone}: {lpm} L/min, brukar vara {avg}. Kontrollera filter, ventil eller rör.",
        "reminder_title": "Bevattning snart",
        "reminder_body": "{name} startar kl. {time} ({n} min).",
        "reminder_skip": "Hoppa över i dag",
        "reminder_run": "Vattna nu",
    },
    "da": {
        "valve_start": "{zone}: vanding startet, {n} min",
        "valve_done": "{zone} vandet {n} min",
        "valve_stopped": "{zone}: vanding stoppet",
        "valve_failed": "{zone}: ventilen åbnede ikke",
        "cycle_start": "{plan}: plan startet, {n} min",
        "cycle_done": "{plan}: plan færdig",
        "cycle_stopped": "{plan}: plan stoppet",
        "skip_rain": "{name} sprunget over: det regner",
        "skip_forecast": "{name} sprunget over: der er regn i vente",
        "skip_rain_delay": "{name} sprunget over: regnpause",
        "skip_moisture": "{name} sprunget over: jorden er fugtig nok",
        "skip_condition": "{name} sprunget over: en betingelse var ikke opfyldt",
        "rain_pause_all": "Vanding sat på pause i {hours} t (regn)",
        "rain_pause_zones": "{zones}: vanding sat på pause i {hours} t (regn)",
        "rain_pause_end_all": "Regnpausen er slut for alle zoner",
        "rain_pause_end_zones": "Regnpausen er slut: {zones}",
        "leak": "Mulig lækage: vandet løber ({value}), selvom ingen zone kører",
        "high_flow": "Højt flow ({value}) under vanding af {zones}",
        "stopped_all": "Al vanding er stoppet.",
        "low_flow": "Lavt flow på {zone}: {lpm} L/min, normalt {avg}. Tjek filter, ventil eller rør.",
        "reminder_title": "Vanding snart",
        "reminder_body": "{name} starter kl. {time} ({n} min).",
        "reminder_skip": "Spring over i dag",
        "reminder_run": "Vand nu",
    },
    "nb": {
        "valve_start": "{zone}: vanning startet, {n} min",
        "valve_done": "{zone} vannet {n} min",
        "valve_stopped": "{zone}: vanning stoppet",
        "valve_failed": "{zone}: ventilen åpnet seg ikke",
        "cycle_start": "{plan}: plan startet, {n} min",
        "cycle_done": "{plan}: plan ferdig",
        "cycle_stopped": "{plan}: plan stoppet",
        "skip_rain": "{name} hoppet over: det regner",
        "skip_forecast": "{name} hoppet over: regn er varslet",
        "skip_rain_delay": "{name} hoppet over: regnpause",
        "skip_moisture": "{name} hoppet over: jorda er fuktig nok",
        "skip_condition": "{name} hoppet over: en betingelse var ikke oppfylt",
        "rain_pause_all": "Vanning satt på pause i {hours} t (regn)",
        "rain_pause_zones": "{zones}: vanning satt på pause i {hours} t (regn)",
        "rain_pause_end_all": "Regnpausen er over for alle soner",
        "rain_pause_end_zones": "Regnpausen er over: {zones}",
        "leak": "Mulig lekkasje: vann renner ({value}) selv om ingen sone kjører",
        "high_flow": "Høy gjennomstrømning ({value}) under vanning av {zones}",
        "stopped_all": "All vanning er stoppet.",
        "low_flow": "Lav gjennomstrømning på {zone}: {lpm} L/min, vanligvis {avg}. Sjekk filter, ventil eller rør.",
        "reminder_title": "Vanning snart",
        "reminder_body": "{name} starter kl. {time} ({n} min).",
        "reminder_skip": "Hopp over i dag",
        "reminder_run": "Vann nå",
    },
    "fi": {
        "valve_start": "{zone}: kastelu alkoi, {n} min",
        "valve_done": "{zone} kasteltu {n} min",
        "valve_stopped": "{zone}: kastelu pysäytetty",
        "valve_failed": "{zone}: venttiili ei auennut",
        "cycle_start": "{plan}: suunnitelma alkoi, {n} min",
        "cycle_done": "{plan}: suunnitelma valmis",
        "cycle_stopped": "{plan}: suunnitelma pysäytetty",
        "skip_rain": "{name} ohitettu: sataa",
        "skip_forecast": "{name} ohitettu: sadetta ennustetaan",
        "skip_rain_delay": "{name} ohitettu: sadetauko",
        "skip_moisture": "{name} ohitettu: maa on tarpeeksi kostea",
        "skip_condition": "{name} ohitettu: ehto ei täyttynyt",
        "rain_pause_all": "Kastelu tauolla {hours} h (sade)",
        "rain_pause_zones": "{zones}: kastelu tauolla {hours} h (sade)",
        "rain_pause_end_all": "Sadetauko päättyi kaikilla alueilla",
        "rain_pause_end_zones": "Sadetauko päättyi: {zones}",
        "leak": "Mahdollinen vuoto: vettä virtaa ({value}), vaikka mikään alue ei ole käynnissä",
        "high_flow": "Suuri virtaama ({value}) alueiden {zones} kastelun aikana",
        "stopped_all": "Kaikki kastelu pysäytetty.",
        "low_flow": "Pieni virtaama alueella {zone}: {lpm} l/min, yleensä {avg}. Tarkista suodatin, venttiili tai putki.",
        "reminder_title": "Kastelu pian",
        "reminder_body": "{name} alkaa klo {time} ({n} min).",
        "reminder_skip": "Ohita tänään",
        "reminder_run": "Kastele nyt",
    },
}


# Languages that write a decimal comma (BUG-027): "1,5 Std.", not "1.5 Std.".
DECIMAL_COMMA = frozenset({"de", "es", "fr", "it", "nl", "pt", "ru", "uk", "pl", "sv", "da", "nb", "fi"})


def fmt_number(value: Any, lang: str = "en") -> str:
    """24.0 -> "24", 0.5 -> "0.5" ("0,5" in a decimal-comma language), 12.345 -> "12.3"."""
    try:
        text = f"{round(float(value), 1):g}"
    except (TypeError, ValueError):
        return str(value)
    return text.replace(".", ",") if lang in DECIMAL_COMMA else text


def notify_text(lang: str, key: str, **params: Any) -> str:
    """A notification text in a panel language (English when the language or key is missing)."""
    table = NOTIFY_TEXT.get(lang) or NOTIFY_TEXT["en"]
    template = table.get(key) or NOTIFY_TEXT["en"][key]
    return template.format(**params)
